Neos:
  Neos:
    fusion:
      autoInclude:
        Carbon.CBD: true
    userInterface:
      translation:
        autoInclude:
          Carbon.CBD:
            - Main
    Ui:
      resources:
        javascript:
          Carbon.CBD.Plugin:
            resource: 'resource://Carbon.CBD/Public/Plugin.js'
